### ISSUE TITLE
How disable fetch DELIVERY type?

### ISSUE THREAD

**Issue by vborodov** [epctex/binance-futures-listener#1]
?

**Comment by tugkan** [comment]
Hey @vborodov 

Thank you very much for reaching out. We just deployed a new version where you can define which `tradeType`s you want to fetch. It should be `ALL`, `PERPETUAL` or `DELIVERY`. Within this approach, you can disable fetching of a certain type. Please use the latest version for the best experience.

Please let me know if there is anything that I can assist you with,
Best
